id: 1bb8adddea2942e7a8946a337158b875
initial_creation_type: ocr
source_metadata:
  volumes:
    2aa36dada96d4e92a12268c8182f30ee:
      base_file: v061.txt
      image_group_id: I1PD95907
      title: ''
      total_pages: 1557
      volume_number: 62
